spring:
  application:
    name:
      mod-record-specifications
  datasource:
    hikari:
      connectionTimeout: ${DB_CONNECTION_TIMEOUT:30000}
      idleTimeout: ${DB_IDLE_TIMEOUT:600000}
      keepaliveTime: ${DB_KEEPALIVE_TIME:0}
      maxLifetime: ${DB_MAX_LIFETIME:1800000}
      validationTimeout: ${DB_VALIDATION_TIMEOUT:5000}
      maximumPoolSize: ${DB_MAXPOOLSIZE:10}
      minimumIdle: ${DB_MINIMUM_IDLE:10}
      initializationFailTimeout: ${DB_INITIALIZATION_FAIL_TIMEOUT:30000}
      leakDetectionThreshold: ${DB_LEAK_DETECTION_THRESHOLD:60000}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
    password: ${DB_PASSWORD:folio_admin}
    username: ${DB_USERNAME:folio_admin}
  jpa:
    properties:
      hibernate:
        show_sql: false
        ddl-auto: validate
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  cloud:
    openfeign:
      okhttp:
        enabled: true
  jackson:
    default-property-inclusion: NON_NULL
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      key-store-password: ${KAFKA_SSL_KEYSTORE_PASSWORD:}
      key-store-location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
    producer:
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 5

folio:
  kafka:
    topics:
      - name: specification-storage.specification.updated
        numPartitions: ${KAFKA_SPECIFICATION_UPDATE_TOPIC_PARTITIONS:1}
        replicationFactor: ${KAFKA_SPECIFICATION_UPDATE_TOPIC_REPLICATION_FACTOR:}
  logging:
    request:
      enabled: true
    feign:
      enabled: true

server.port: 8081

management:
  endpoints:
    web:
      exposure:
        include: info,health,liquibase,threaddump,heapdump,loggers
      base-path: /admin
  endpoint:
    loggers:
      enabled: true
      
logging:
  level:
    org.folio.spring.filter.LoggingRequestFilter: DEBUG
    org.folio.spring.i18n.model.TranslationMap: FATAL