openapi: 3.0.3
info:
  version: 1.0.0
  title: Record Specifications API
  description: API for managing record specifications and validating records against them
  contact:
    name: Spitfire team

servers:
  - url: https://{environment}-okapi.ci.folio.org
    description: Development environments.
    variables:
      environment:
        default: folio-dev-spitfire
        enum:
          - folio-dev-spitfire
          - folio-perf-spitfire
  - url: https://folio-{environment}-okapi.dev.folio.org
    description: Reference environments.
    variables:
      environment:
        default: snapshot
        enum:
          - snapshot
          - snapshot-2

tags:
  - name: specification-storage
    description: Provides API for managing specifications.
  - name: specification-storage-fields
    description: Provides API for managing specification fields.
  - name: specification-storage-indicators
    description: Provides API for managing specification field indicators.

paths:
  /specification-storage/specifications:
    $ref: 'paths/specification-storage/specifications-path.yaml'
  /specification-storage/specifications/{specificationId}/sync:
    $ref: 'paths/specification-storage/specification-sync-path.yaml'
  /specification-storage/specifications/{specificationId}/rules:
    $ref: 'paths/specification-storage/specification-rules-path.yaml'
  /specification-storage/specifications/{specificationId}/rules/{id}:
    $ref: 'paths/specification-storage/specification-rules-by-id-path.yaml'
  /specification-storage/specifications/{specificationId}/fields:
    $ref: 'paths/specification-storage/specification-fields-path.yaml'
  /specification-storage/fields/{id}:
    $ref: 'paths/specification-storage/fields-by-id-path.yaml'
  /specification-storage/fields/{fieldId}/subfields:
    $ref: 'paths/specification-storage/field-subfields-path.yaml'
  /specification-storage/fields/{fieldId}/indicators:
    $ref: 'paths/specification-storage/field-indicators-path.yaml'
  /specification-storage/indicators/{indicatorId}:
    $ref: 'paths/specification-storage/field-indicators-by-id-path.yaml'
  /specification-storage/indicators/{indicatorId}/indicator-codes:
    $ref: 'paths/specification-storage/indicator-codes-path.yaml'
  /specification-storage/indicator-codes/{indicatorCodeId}:
    $ref: 'paths/specification-storage/indicator-codes-by-id-path.yaml'
